# -*- coding: utf-8 -*-
"""History's Dumbest Wars — FULL 10-12 min script (192 beats, 26 items).
Beat rule (user + measured 16092.mp4): 10-12 words per beat, 2-5 s per beat.
One image per beat. Image holds EXACTLY the VO length (+0.15 s tail) — never stretched.
Parts = 10 beats each. This file is the single source of truth for all parts.
"""
BEATS = [
# ---------- INTRO (Part 1: beats 1-4) ----------
dict(n=1,  part=1, item="INTRO",
     text="Some wars are fought over land or religion, sadly not every one.",
     env="desk", scene="one stick character at a dark wooden desk, scratching its head over a messy pile of old maps and books",
     face="confused raised brows, small open mouth"),
dict(n=2,  part=1, item="INTRO",
     text="History's dumbest wars were fought over a pig and a bucket.",
     env="farm", scene="one stick character proudly holding a piglet in one arm and a wooden bucket in the other, a croissant on the ground",
     face="smug smile with pink tongue, relaxed brows"),
dict(n=3,  part=1, item="INTRO",
     text="I ranked them by stupidity, so settle in and enjoy the show.",
     env="desk", scene="one stick character standing on the desk holding a big golden trophy up high",
     face="proud smile with pink tongue"),
dict(n=4,  part=1, item="INTRO",
     text="Each story gets only a few seconds, so please do not blink.",
     env="desk", scene="one stick character holding a giant hourglass, sand pouring",
     face="amused open smile, raised brows"),
# ---------- 1. PIG WAR 1859 (Part 1: beats 5-10) ----------
dict(n=5,  part=1, item="Pig War 1859",
     text="Number one on our list is the Pig War of eighteen fifty-nine.",
     env="farm", scene="one stick farmer presenting a big happy pig, two tiny stick soldiers saluting behind",
     face="cheerful open smile"),
dict(n=6,  part=1, item="Pig War 1859",
     text="A British pig ate an American farmer's entire pile of beloved potatoes.",
     env="farm", scene="one stick farmer horrified, big pig happily munching a pile of potatoes",
     face="shocked open mouth, raised worried brows"),
dict(n=7,  part=1, item="Pig War 1859",
     text="The farmer shot the pig, and then the neighbors started to argue.",
     env="farm", scene="one angry stick farmer shaking a fist, pig lying on the grass with X eyes and tongue out",
     face="angry slanted brows, tight mouth"),
dict(n=8,  part=1, item="Pig War 1859",
     text="Both powerful empires sent huge armies to the little San Juan Island.",
     env="sea", scene="one stick soldier waving a flag on a green island shore, rowboats and a ship behind",
     face="determined neutral brows, small line mouth"),
dict(n=9,  part=1, item="Pig War 1859",
     text="The soldiers camped for twelve long years, eating and playing board games.",
     env="farm", scene="one stick soldier relaxing in a camp chair by a tent and campfire, playing cards",
     face="bored sleepy half-closed dot eyes, small yawn"),
dict(n=10, part=1, item="Pig War 1859",
     text="The only real casualty of the whole war was the poor pig.",
     env="farm", scene="one stick farmer saluting sadly at a tiny mound with a blank gravestone",
     face="sad funny frown, raised sad brows"),
# ---------- 2. WAR OF THE BUCKET 1325 (Part 2: beats 11-17) ----------
dict(n=11, part=2, item="Bucket War 1325",
     text="Number two is the War of the Bucket in thirteen twenty-five.",
     env="village", scene="one stick knight proudly holding up a wooden bucket like a trophy, castle behind",
     face="proud smug smile"),
dict(n=12, part=2, item="Bucket War 1325",
     text="Italian soldiers stole a plain wooden bucket right from a town well.",
     env="village", scene="one stick soldier tiptoeing away with a wooden bucket, stone well behind",
     face="mischievous smirk, sly raised brow"),
dict(n=13, part=2, item="Bucket War 1325",
     text="Its owner treated the theft as an insult and declared war.",
     env="village", scene="one stick noble pointing angrily from a castle window, soldiers with spears below",
     face="angry slanted brows, shouting open mouth"),
dict(n=14, part=2, item="Bucket War 1325",
     text="Knights died charging hills while the bucket just sat inside the tower.",
     env="hill", scene="one stick knight with sword running up a green hill, castle tower on top",
     face="panicked worried brows, open shout mouth"),
dict(n=15, part=2, item="Bucket War 1325",
     text="Around two thousand people died over one simple wooden bucket of oak.",
     env="hill", scene="one sad stick knight sitting on the grass, wooden bucket beside him, weapon resting down",
     face="tired sad droopy brows, small frown"),
dict(n=16, part=2, item="Bucket War 1325",
     text="The precious bucket still exists, and you can visit it today.",
     env="room", scene="one stick guard standing proudly next to a shining wooden bucket on a pedestal in a museum hall",
     face="proud flat brows, small smile"),
dict(n=17, part=2, item="Bucket War 1325",
     text="Stupidity rating, a perfect ten wooden buckets out of ten.",
     env="room", scene="one stick character holding ten tiny wooden buckets stacked in a wagon",
     face="exaggerated open laugh, tongue out"),
# ---------- 3. PASTRY WAR 1838 (Part 2: beats 18-24) ----------
dict(n=18, part=2, item="Pastry War 1838",
     text="Number three on our list is the Pastry War of eighteen thirty-eight.",
     env="city", scene="one stick chef in a tall white hat holding a giant croissant like a trophy",
     face="proud happy smile"),
dict(n=19, part=2, item="Pastry War 1838",
     text="A French chef's beloved bakery got wrecked during a Mexico City riot.",
     env="city", scene="one stick chef crying, broken bakery stand and spilled flour around",
     face="crying sad brows, open wail mouth"),
dict(n=20, part=2, item="Pastry War 1838",
     text="France demanded six hundred thousand pesos for the completely ruined pastries.",
     env="city", scene="one stick French official holding a long paper scroll, chef nodding beside a table of pastries",
     face="stern demanding flat brows, small mouth"),
dict(n=21, part=2, item="Pastry War 1838",
     text="Mexico refused to pay, so thirty French ships blockaded the entire coast.",
     env="sea", scene="one stick captain on a sailing ship, many warships lined up on the horizon",
     face="confident flat brows, smug line mouth"),
dict(n=22, part=2, item="Pastry War 1838",
     text="The chef became a national hero without even trying to be one.",
     env="city", scene="one stick chef blushing, people throwing flowers, street celebration",
     face="embarrassed happy smile, blush marks"),
dict(n=23, part=2, item="Pastry War 1838",
     text="Mexico finally paid every peso, and France got all its pastry money.",
     env="city", scene="one stick banker counting a tall stack of coins, chef smiling with a croissant",
     face="greedy happy grin, wide eyes"),
dict(n=24, part=2, item="Pastry War 1838",
     text="Stupidity rating, eight absolutely delicious French pastries out of ten.",
     env="city", scene="one stick character holding a tray of eight big pastries, weight straining",
     face="strained funny effort face, wide eyes"),
# ---------- 4. EMU WAR 1932 (Part 3: beats 25-31) ----------
dict(n=25, part=3, item="Emu War 1932",
     text="Number four is the Great Emu War of Australia, in nineteen thirty-two.",
     env="desert", scene="one stick farmer pleading with a soldier, tall emus in the background",
     face="desperate pleading raised brows, open mouth"),
dict(n=26, part=3, item="Emu War 1932",
     text="Desperate farmers begged the army to destroy twenty thousand giant emus.",
     env="desert", scene="one stick soldier with a big machine gun on a cart, angry emus lined up",
     face="serious determined flat brows"),
dict(n=27, part=3, item="Emu War 1932",
     text="So the soldiers arrived with machine guns and plenty of loaded ammunition.",
     env="desert", scene="one stick soldier posing proudly with a machine gun on a truck, ammo boxes",
     face="confident smug grin"),
dict(n=28, part=3, item="Emu War 1932",
     text="But the clever emus dodged every bullet and scattered at full speed.",
     env="desert", scene="one emu running fast, dust cloud, soldier aiming but missing, bullets in dots",
     face="shocked open mouth on soldier"),
dict(n=29, part=3, item="Emu War 1932",
     text="The emus split into tiny groups and easily outran the exhausted soldiers.",
     env="desert", scene="three small groups of emus running in different directions, confused soldiers",
     face="confused raised brows, small frown"),
dict(n=30, part=3, item="Emu War 1932",
     text="Even the machine gun got stuck, making this war a total joke.",
     env="desert", scene="one stick soldier shaking a stuck machine gun on a truck, laughing emu nearby",
     face="frustrated angry brows, gritted mouth"),
dict(n=31, part=3, item="Emu War 1932",
     text="The army finally withdrew, and the proud emus declared their victory.",
     env="desert", scene="one proud emu wearing a little crown, army marching away sadly",
     face="emus smug, soldiers sad frowny"),
# ---------- 5. MOLASSES FLOOD 1919 (Part 3: beats 32-38) ----------
dict(n=32, part=3, item="Molasses 1919",
     text="Number five is Boston's famous Great Molasses Flood of nineteen nineteen.",
     env="city", scene="one stick character pointing at a giant tank on a brown city street",
     face="worried raised brows, small open mouth"),
dict(n=33, part=3, item="Molasses 1919",
     text="A giant tank burst open and sent syrup racing through the streets.",
     env="city", scene="one stick character running from a huge brown syrup wave, buildings behind",
     face="terrified wide dot eyes, open scream mouth"),
dict(n=34, part=3, item="Molasses 1919",
     text="The twenty-five foot wave of hot molasses crushed nearly everything.",
     env="city", scene="one stick character buried chest-deep in brown syrup, hats and carts floating",
     face="shocked wide open mouth"),
dict(n=35, part=3, item="Molasses 1919",
     text="Sadly, twenty-one poor people were buried in the sticky brown mess.",
     env="city", scene="one stick person covered in syrup holding a small flag, crowd wading in goo",
     face="sad tired droopy brows"),
dict(n=36, part=3, item="Molasses 1919",
     text="The entire city smelled like pancakes for the next few decades.",
     env="city", scene="one stick character holding their nose, syrup dripping from buildings",
     face="grossed-out squinted eyes, scrunched mouth"),
dict(n=37, part=3, item="Molasses 1919",
     text="Officials blamed the tank makers, and not the sweet sticky molasses.",
     env="city", scene="one stick official pointing accusingly at a tiny tank, jury of stick characters",
     face="serious stern flat brows"),
dict(n=38, part=3, item="Molasses 1919",
     text="Stupidity rating, nine extra sticky gallons of syrup out of ten.",
     env="city", scene="one stick character holding a giant dripping syrup barrel, proud but sticky",
     face="funny proud grin, sticky drips"),
# ---------- 6. STRAY DOG WAR 1925 (Part 4: beats 39-45) ----------
dict(n=39, part=4, item="Stray Dog 1925",
     text="Number six is the War of the Stray Dog of nineteen twenty-five.",
     env="village", scene="one happy stray dog with a brown patch running across a dirt road, border sign sticks in ground",
     face="happy dog tongue out"),
dict(n=40, part=4, item="Stray Dog 1925",
     text="A Greek soldier chased a stray dog across the border without thinking.",
     env="village", scene="one stick soldier running after the dog, border marker behind",
     face="determined chasing face, tight mouth"),
dict(n=41, part=4, item="Stray Dog 1925",
     text="Bulgarian guards shot him, and Greece then invaded the neighboring Bulgaria.",
     env="village", scene="one stick Greek general pointing forward, soldiers marching, worried guards",
     face="angry demanding brows"),
dict(n=42, part=4, item="Stray Dog 1925",
     text="Bulgaria asked the brand new League of Nations to intervene for help.",
     env="village", scene="one stick diplomat on a stage waving a paper, globe and flags in background",
     face="pleading serious brows"),
dict(n=43, part=4, item="Stray Dog 1925",
     text="Greece had to pay fines, and the stray dog simply vanished completely.",
     env="village", scene="one stick judge handing a fine paper to a sad Greek general, empty road",
     face="embarrassed frown"),
dict(n=44, part=4, item="Stray Dog 1925",
     text="Nobody officially blamed the dog, but everybody secretly knew the truth.",
     env="village", scene="one stick dog sitting innocently with big eyes, crowd whispering",
     face="innocent wide dot eyes, tiny smile"),
dict(n=45, part=4, item="Stray Dog 1925",
     text="Stupidity rating, seven completely innocent stray dogs out of ten.",
     env="village", scene="one stick character holding a leash with seven funny dogs tied together",
     face="amused laugh, tongue out"),
# ---------- 7. ANGLO-ZANZIBAR 1896 (Part 4: beats 46-52) ----------
dict(n=46, part=4, item="Zanzibar 1896",
     text="Number seven is the Anglo-Zanzibar War of eighteen ninety-six, yes.",
     env="palace", scene="one stick sultan in gold robes on a throne, palm trees outside",
     face="stubborn proud frown"),
dict(n=47, part=4, item="Zanzibar 1896",
     text="A stubborn new sultan refused to bow to British colonial rule.",
     env="palace", scene="one stick sultan crossing arms, British officer with a list looking stern",
     face="stubborn defiant slanted brows"),
dict(n=48, part=4, item="Zanzibar 1896",
     text="The Royal Navy bombarded his palace for just thirty-eight tiny minutes.",
     env="sea", scene="one stick captain on a warship, cannon smoke, palace on the coast",
     face="serious concentrating flat brows"),
dict(n=49, part=4, item="Zanzibar 1896",
     text="It officially holds the world record for the shortest war ever.",
     env="palace", scene="one stick character holding a giant stopwatch, palace behind",
     face="amazed raised brows, open mouth"),
dict(n=50, part=4, item="Zanzibar 1896",
     text="Hundreds died while exactly one British sailor got a minor injury.",
     env="palace", scene="one stick sailor with a small bandage, sad people in the background",
     face="awkward sheepish grin"),
dict(n=51, part=4, item="Zanzibar 1896",
     text="The new sultan signed everything the British had originally wanted from him.",
     env="palace", scene="one stick sultan signing a long paper, British officer nodding",
     face="grumpy defeated frown"),
dict(n=52, part=4, item="Zanzibar 1896",
     text="Stupidity rating, eight big shiny naval cannons out of ten.",
     env="sea", scene="one stick character holding eight tiny cannons, proud but strained",
     face="funny strained effort face"),
# ---------- 8. FOOTBALL WAR 1969 (Part 5: beats 53-59) ----------
dict(n=53, part=5, item="Football War 1969",
     text="Number eight is the truly legendary Football War of nineteen sixty-nine.",
     env="stadium", scene="one stick player kicking a soccer ball on a green field, stadium stands",
     face="determined confident brows"),
dict(n=54, part=5, item="Football War 1969",
     text="El Salvador and Honduras argued about soccer and about bad immigration policies.",
     env="stadium", scene="two stick players arguing nose to nose over a soccer ball",
     face="both angry slanted brows, shouting"),
dict(n=55, part=5, item="Football War 1969",
     text="A tense losing qualifier match made both entire sides completely furious.",
     env="stadium", scene="one stick goalie dropping a soccer ball, angry crowd shapes behind",
     face="horrified wide eyes, open mouth"),
dict(n=56, part=5, item="Football War 1969",
     text="They invaded each other for about one hundred hours, yes one hundred.",
     env="hill", scene="one stick general pointing with a soccer ball on a pole instead of a flag, tanks",
     face="angry determined frown"),
dict(n=57, part=5, item="Football War 1969",
     text="Over three thousand people died while the whole world just watched it.",
     env="hill", scene="one sad stick soldier sitting with a soccer ball, memorial marker behind",
     face="sad tired droopy brows"),
dict(n=58, part=5, item="Football War 1969",
     text="Soccer fans finally lost their minds, and the silly war ended fast.",
     env="stadium", scene="one stick referee blowing a whistle, cheering crowd, flags waving",
     face="relieved happy smile"),
dict(n=59, part=5, item="Football War 1969",
     text="Stupidity rating, eleven very angry soccer footballs out of ten.",
     env="stadium", scene="one stick character buried under eleven soccer balls, feet sticking out",
     face="feet only, funny chaos"),
# ---------- 9. JENKINS' EAR 1739 (Part 5: beats 60-66) ----------
dict(n=60, part=5, item="Jenkins' Ear 1739",
     text="Number nine is the War of Jenkins' Ear, from seventeen thirty-nine.",
     env="room", scene="one stick captain in a hat holding a small glass jar, Parliament hall behind",
     face="dramatic serious brows, open speech mouth"),
dict(n=61, part=5, item="Jenkins' Ear 1739",
     text="A British captain showed his severed ear off to the entire Parliament.",
     env="room", scene="one stick captain holding the jar high, shocked stick MPs leaning back",
     face="dramatic proud face, shocked audience"),
dict(n=62, part=5, item="Jenkins' Ear 1739",
     text="Spanish customs officers allegedly cut it off him years earlier at sea.",
     env="sea", scene="one stick Spanish officer with a sword, angry captain holding his ear on a ship deck",
     face="stern, captain in pain with sweaty marks"),
dict(n=63, part=5, item="Jenkins' Ear 1739",
     text="Everyone gasped in shock, and Britain declared war on Spain immediately.",
     env="room", scene="one stick minister signing a big paper, crowd of MPs gasping",
     face="excited dramatic open mouths"),
dict(n=64, part=5, item="Jenkins' Ear 1739",
     text="The ear became the most famous body part in all human history.",
     env="room", scene="one stick character presenting a giant jar on a pedestal, spotlight",
     face="proud showman smile"),
dict(n=65, part=5, item="Jenkins' Ear 1739",
     text="The war dragged on, but the preserved ear remained the main star.",
     env="room", scene="one stick character reading a huge scroll, jar on a stool beside",
     face="bored flat brows, small yawn"),
dict(n=66, part=5, item="Jenkins' Ear 1739",
     text="Stupidity rating, seven point five invisible ears out of ten.",
     env="room", scene="one stick character confused holding seven and a half jars in a row",
     face="confused tilted head, small frown"),
# ---------- 10. KETTLE WAR 1784 (Part 6: beats 67-73) ----------
dict(n=67, part=6, item="Kettle War 1784",
     text="Number ten is the super short Kettle War of seventeen eighty-four.",
     env="sea", scene="one stick sailor showing a shiny metal kettle on a wooden ship deck",
     face="proud funny grin"),
dict(n=68, part=6, item="Kettle War 1784",
     text="A Dutch ship refused to lower its flag to the Austrian forces.",
     env="sea", scene="one stick Dutch captain crossing arms, flag high on mast, angry Austrian ship",
     face="stubborn defiant frown"),
dict(n=69, part=6, item="Kettle War 1784",
     text="One cannonball was fired, and it hit a poor cooking kettle.",
     env="sea", scene="one stick cannon firing a round cannonball, kettle in the air taking the hit",
     face="surprised open mouths"),
dict(n=70, part=6, item="Kettle War 1784",
     text="The kettle exploded everywhere, and the poor crew quickly surrendered the ship.",
     env="sea", scene="one wet stick sailor raising arms, kettle pieces flying, steam",
     face="panicked shocked open mouth"),
dict(n=71, part=6, item="Kettle War 1784",
     text="Nobody died except the kettle, which is still genuinely funny today.",
     env="sea", scene="one stick sailor saluting a sad cracked kettle on the deck",
     face="amused smirk, one raised brow"),
dict(n=72, part=6, item="Kettle War 1784",
     text="The whole famous war lasted barely thirty minutes from beginning to end.",
     env="sea", scene="one stick character holding a tiny hourglass, ship behind",
     face="amazed raised brows, open mouth"),
dict(n=73, part=6, item="Kettle War 1784",
     text="Stupidity rating, six badly shattered cook kettles out of ten.",
     env="sea", scene="one stick character holding six cracked kettles, funny strained face",
     face="funny strain, wide eyes"),
# ---------- 11. 335 YEARS' WAR (Part 6: beats 74-80) ----------
dict(n=74, part=6, item="335 Years War",
     text="Number eleven is the Three Hundred Thirty-Five Years' War on our list.",
     env="sea", scene="one stick Dutch captain waving from a ship, tiny islands on the horizon",
     face="serious declaring smile"),
dict(n=75, part=6, item="335 Years War",
     text="The Dutch declared war on the Scilly Isles in sixteen fifty-one.",
     env="sea", scene="one stick officer reading a long declaration paper on a ship deck",
     face="solemn serious flat brows"),
dict(n=76, part=6, item="335 Years War",
     text="Nobody fired a shot, nobody fought, and nobody even really cared.",
     env="sea", scene="two stick sailors shrugging at each other, cannons covered in cobwebs",
     face="bored sleepy eyes, tiny yawn"),
dict(n=77, part=6, item="335 Years War",
     text="In nineteen eighty-six, historians finally found the old official declaration.",
     env="room", scene="one stick historian in glasses holding up a dusty old paper scroll",
     face="excited amazed raise brows, open smile"),
dict(n=78, part=6, item="335 Years War",
     text="The Dutch and the Scillies finally signed a proper peace treaty together.",
     env="room", scene="two stick diplomats shaking hands over a peace paper, flags behind",
     face="happy relieved smiles"),
dict(n=79, part=6, item="335 Years War",
     text="Signing the peace treaty somehow took longer than the entire war did.",
     env="room", scene="one stick diplomat holding a giant paper, pen, funny exhaustion",
     face="tired funny strain, sweat marks"),
dict(n=80, part=6, item="335 Years War",
     text="Stupidity rating, ten completely forgotten peace treaties out of ten.",
     env="room", scene="one stick character carrying a stack of ten rolled treaties, nearly falling",
     face="strained funny effort face"),
# ---------- 12. WAR OF THE HATS 1741 (Part 7: beats 81-87) ----------
dict(n=81, part=7, item="Hat War 1741",
     text="Number twelve is the silly War of the Hats of seventeen forty-one.",
     env="room", scene="one stick noble wearing a huge fancy hat, posing on a podium",
     face="vain proud smile"),
dict(n=82, part=7, item="Hat War 1741",
     text="Swedish politicians named their entire political party after fancy hats.",
     env="room", scene="one stick politician holding the huge hat up like a crown, small parliament",
     face="proud dramatic grin"),
dict(n=83, part=7, item="Hat War 1741",
     text="The rival political party wore nightcaps, and history is simply incredible.",
     env="room", scene="one stick politician wearing a floppy nightcap, yawning, other side with hats",
     face="sleepy smug grin"),
dict(n=84, part=7, item="Hat War 1741",
     text="The hat party declared war on Russia purely for glory and hats.",
     env="hill", scene="one stick general in the huge hat pointing toward snowy hills, army behind",
     face="overconfident smug smile"),
dict(n=85, part=7, item="Hat War 1741",
     text="Russia crushed them completely, and Sweden lost plenty of valuable land.",
     env="hill", scene="one stick general in a broken hat, hat on the ground, sad army walking away",
     face="defeated sad droopy brows"),
dict(n=86, part=7, item="Hat War 1741",
     text="The nightcaps won, and history ended up laughing at absolutely everyone involved.",
     env="room", scene="one stick character in a nightcap laughing hard, hats in bin behind",
     face="huge open laugh, tears of laughter"),
dict(n=87, part=7, item="Hat War 1741",
     text="Stupidity rating, five absolutely elegant party hats out of ten.",
     env="room", scene="one stick character wearing five hats stacked, wobbling",
     face="funny strained proud face"),
# ---------- 13. GOLDEN STOOL 1900 (Part 7: beats 88-94) ----------
dict(n=88, part=7, item="Golden Stool 1900",
     text="Number thirteen is the War of the Golden Stool of nineteen hundred.",
     env="jungle", scene="one stick chief sitting on a glowing golden stool, jungle around",
     face="calm proud flat brows"),
dict(n=89, part=7, item="Golden Stool 1900",
     text="A British governor demanded to sit on the Ashanti people's sacred chair.",
     env="jungle", scene="one stick British officer pointing at the glowing golden stool, chiefs angry",
     face="greedy entitled smirk, angry chiefs"),
dict(n=90, part=7, item="Golden Stool 1900",
     text="The Ashanti warriors refused politely and quickly hid the golden stool forever.",
     env="jungle", scene="one stick chief hiding the glowing stool under palm leaves, soldiers searching",
     face="secretive sly smile"),
dict(n=91, part=7, item="Golden Stool 1900",
     text="Fighting broke out briefly, but the golden stool was never ever found.",
     env="jungle", scene="one stick soldier digging a hole, chiefs hiding the stool behind a tree",
     face="frustrated, chiefs amused"),
dict(n=92, part=7, item="Golden Stool 1900",
     text="British soldiers searched a whole country for one single piece of furniture.",
     env="jungle", scene="one stick soldier with a magnifying glass over a jungle, tiny golden light peeking",
     face="confused determined frown"),
dict(n=93, part=7, item="Golden Stool 1900",
     text="The stool remains hidden today, and nobody may ever sit on it.",
     env="jungle", scene="one stick chief guarding a hidden glowing spot, mystery sparkles",
     face="proud secretive smile"),
dict(n=94, part=7, item="Golden Stool 1900",
     text="Stupidity rating, nine very shiny golden stools out of ten.",
     env="jungle", scene="one stick character hugging a glowing golden stool, jungle sparkles",
     face="greedy joyful grin"),
# ---------- 14. TOLEDO WAR 1835 (Part 8: beats 95-101) ----------
dict(n=95, part=8, item="Toledo War 1835",
     text="Number fourteen is the hilarious Toledo War between Ohio and Michigan.",
     env="farm", scene="two stick characters pulling opposite ends of a farm map ribbon, cornfield between",
     face="both stubborn angry brows"),
dict(n=96, part=8, item="Toledo War 1835",
     text="They argued fiercely over one thin strip of perfectly good farm land.",
     env="farm", scene="one stick character measuring a very thin strip of cornfield with a giant ruler",
     face="serious petty frown"),
dict(n=97, part=8, item="Toledo War 1835",
     text="Ohio sent militia with guns, and Michigan sent its militia too.",
     env="hill", scene="two stick groups of tiny militia facing off across a hill, picket signs",
     face="angry but nervous faces"),
dict(n=98, part=8, item="Toledo War 1835",
     text="The only real casualty was a poor sheriff who got stabbed once.",
     env="hill", scene="one stick sheriff with a small bandage waving, everyone gasping",
     face="dramatic overdramatic pain face"),
dict(n=99, part=8, item="Toledo War 1835",
     text="Michigan got the Upper Peninsula as its giant consolation prize for losing.",
     env="farm", scene="one stick Michigan character receiving a giant land gift box, Ohio walks away smug",
     face="happy surprised, Ohio smug"),
dict(n=100, part=8, item="Toledo War 1835",
     text="Today the states still joke about that silly little strip of land.",
     env="farm", scene="two stick characters laughing together at a tiny corn strip with a funny ruler",
     face="both laughing open mouths"),
dict(n=101, part=8, item="Toledo War 1835",
     text="Stupidity rating, eight very angry cornfields out of a total ten.",
     env="farm", scene="one stick character with eight corn stalks in arms, funny effort",
     face="strained proud face"),
# ---------- 15. AROOSTOOK WAR 1838 (Part 8: beats 102-108) ----------
dict(n=102, part=8, item="Aroostook 1838",
     text="Number fifteen is the Aroostook War of eighteen thirty-eight, exactly.",
     env="forest", scene="one stick lumberjack with an axe and a giant log, forest of pines",
     face="proud tough grin"),
dict(n=103, part=8, item="Aroostook 1838",
     text="Americans and Canadians argued fiercely over a thick timber forest.",
     env="forest", scene="two stick lumberjacks arguing over a map in the forest, axes in hands",
     face="angry stubborn brows"),
dict(n=104, part=8, item="Aroostook 1838",
     text="The lumberjacks fought with fists, axes, and giant wooden logs.",
     env="forest", scene="one stick lumberjack raising a rolled log like a club, sawdust flying",
     face="battle angry face"),
dict(n=105, part=8, item="Aroostook 1838",
     text="Both sides sent troops who mostly just chopped down many trees.",
     env="forest", scene="one stick soldier chopping a tree with an axe, other soldiers watching bored",
     face="bored serious flat face"),
dict(n=106, part=8, item="Aroostook 1838",
     text="The only victims were innocent trees, and maybe one very sad ox.",
     env="forest", scene="one sad ox standing by a chopped stump, stick farmer patting it",
     face="sad ox eyes, farmer gentle frown"),
dict(n=107, part=8, item="Aroostook 1838",
     text="Peace finally arrived through a clever map making agreement between everyone.",
     env="room", scene="two stick diplomats drawing a line on a giant map together, rulers and pens",
     face="satisfied relieved smiles"),
dict(n=108, part=8, item="Aroostook 1838",
     text="Stupidity rating, seven tall maple tree logs out of ten.",
     env="forest", scene="one stick character carrying seven stacked logs, funny strain",
     face="strained effort funny face"),
# ---------- 16. COD WARS 1958 (Part 9: beats 109-115) ----------
dict(n=109, part=9, item="Cod Wars 1958",
     text="Number sixteen is the Cod Wars between Iceland and Great Britain.",
     env="sea", scene="one stick Icelandic fisherman proudly holding a giant cod, waves",
     face="proud smug smile"),
dict(n=110, part=9, item="Cod Wars 1958",
     text="Iceland expanded its huge fishing zone, and Britain got extremely furious.",
     env="sea", scene="one stick British captain shaking a fist from his trawler, Iceland zone buoy",
     face="angry red-in-face frown"),
dict(n=111, part=9, item="Cod Wars 1958",
     text="British trawlers rammed ships and cut each other's expensive fishing nets.",
     env="sea", scene="one stick trawler captain with net cut, fisherman shocked, ships ramming",
     face="shocked angry open mouth"),
dict(n=112, part=9, item="Cod Wars 1958",
     text="Iceland's tiny coast guard played ramming games with them for years.",
     env="sea", scene="one stick coast guard boat captain smug, big British ship in the way",
     face="smug confident grin"),
dict(n=113, part=9, item="Cod Wars 1958",
     text="Nobody died, and everyone just kept happily eating their favorite fish.",
     env="sea", scene="one stick person eating fish and chips happily, boats calm behind",
     face="happy munching smile"),
dict(n=114, part=9, item="Cod Wars 1958",
     text="Iceland won bigger fishing rights by the very end of it all.",
     env="sea", scene="one stick Icelandic captain holding a giant trophy shaped like a cod",
     face="victorious proud grin"),
dict(n=115, part=9, item="Cod Wars 1958",
     text="Stupidity rating, frozen codfish eight great fish out of ten.",
     env="sea", scene="one stick character holding six frozen cod, snow, funny strain",
     face="cold funny strained face"),
# ---------- 17. TURBOT WAR 1994 (Part 9: beats 116-122) ----------
dict(n=116, part=9, item="Turbot War 1994",
     text="Number seventeen is the suddenly real Turbot War of nineteen ninety-four.",
     env="sea", scene="one stick fisherman holding a giant flat turbot fish, proud grin",
     face="proud happy smile"),
dict(n=117, part=9, item="Turbot War 1994",
     text="Canada accused Spanish fishing boats of catching too many small turbots.",
     env="sea", scene="one stick Canadian official pointing finger at a fishing boat, scales on paper",
     face="stern accusing flat brows"),
dict(n=118, part=9, item="Turbot War 1994",
     text="Canadian agents boarded a Spanish trawler on the broad open ocean.",
     env="sea", scene="one stick agent climbing onto a trawler with a rope, captain shocked",
     face="determined, captain shocked open mouth"),
dict(n=119, part=9, item="Turbot War 1994",
     text="Spain sent out warships, and the entire world completely lost its mind.",
     env="sea", scene="one stick Spanish warship captain with a flag, tiny trawler behind",
     face="angry dramatic frown"),
dict(n=120, part=9, item="Turbot War 1994",
     text="NATO had to calm down two countries over some very flat fish.",
     env="room", scene="one stick diplomat in a big hall holding a fish, two angry delegates",
     face="awkward strained smile"),
dict(n=121, part=9, item="Turbot War 1994",
     text="A fishing deal was finally signed, and everyone just moved on quietly.",
     env="room", scene="two stick delegates signing paper, fish on the table between",
     face="relieved tired smiles"),
dict(n=122, part=9, item="Turbot War 1994",
     text="Stupidity rating, six totally flat and silly turbot out of ten.",
     env="sea", scene="one stick character holding six flat fish like plates, funny balance",
     face="strained funny effort face"),
# ---------- 18. LOBSTER WAR 1961 (Part 10: beats 123-129) ----------
dict(n=123, part=10, item="Lobster War 1961",
     text="Number eighteen is the Lobster War between France and Brazil.",
     env="sea", scene="one stick French sailor holding a giant red lobster, waves",
     face="proud confident grin"),
dict(n=124, part=10, item="Lobster War 1961",
     text="French ships chased lobsters that crossed into the Brazilian waters.",
     env="sea", scene="one stick French ship captain pointing at lobsters swimming, Brazilian coast",
     face="greedy determined face"),
dict(n=125, part=10, item="Lobster War 1961",
     text="France argued that lobsters swim, so they are totally fair game.",
     env="room", scene="one stick French diplomat pointing at a swimming lobster drawing on a board",
     face="clever smug smile"),
dict(n=126, part=10, item="Lobster War 1961",
     text="Brazil argued lobsters crawl, so they completely belong to them.",
     env="room", scene="one stick Brazilian diplomat pointing at a walking lobster drawing",
     face="angry stubborn frown"),
dict(n=127, part=10, item="Lobster War 1961",
     text="Two tiny navies glared at each other over wandering crustaceans.",
     env="sea", scene="two stick captains glaring across the waves, lobsters between",
     face="both angry stubborn stares"),
dict(n=128, part=10, item="Lobster War 1961",
     text="They finally caught one single lobster, and the crisis faded away.",
     env="sea", scene="one stick sailor holding up a single small lobster, navy ships relaxing",
     face="relieved funny smile"),
dict(n=129, part=10, item="Lobster War 1961",
     text="Stupidity rating, five big red clawed lobsters out of ten.",
     env="sea", scene="one stick character holding five lobsters, claws pinching, funny pain",
     face="funny strained pain, wide eyes"),
# ---------- 19. WATERMELON WAR 1856 (Part 10: beats 130-136) ----------
dict(n=130, part=10, item="Watermelon War 1856",
     text="Number nineteen is the Watermelon War in Panama, eighteen fifty-six.",
     env="city", scene="one stick vendor holding a giant watermelon slice, market stalls",
     face="friendly smiling seller"),
dict(n=131, part=10, item="Watermelon War 1856",
     text="An American refused to pay for a single slice of juicy watermelon.",
     env="city", scene="one stick man walking away with a watermelon slice, angry vendor chasing",
     face="stubborn smug, vendor angry"),
dict(n=132, part=10, item="Watermelon War 1856",
     text="The vendor argued, a huge crowd gathered, and suddenly shots rang out.",
     env="city", scene="crowd of stick characters gathering, vendor waving a watermelon rind",
     face="shocked wide open mouths"),
dict(n=133, part=10, item="Watermelon War 1856",
     text="Hundreds rioted over one fruit, and seventeen people tragically lost their lives.",
     env="city", scene="one sad stick character holding a watermelon, city street quiet",
     face="sad droopy brows"),
dict(n=134, part=10, item="Watermelon War 1856",
     text="The United States sent troops to defend the important melon trade.",
     env="city", scene="one stick soldier guarding a giant watermelon with a flag",
     face="serious but slightly funny stern face"),
dict(n=135, part=10, item="Watermelon War 1856",
     text="Watermelon prices did not change, but the entire world just laughed forever.",
     env="city", scene="one stick vendor laughing, holding a watermelon price sign blank",
     face="laughing open mouth"),
dict(n=136, part=10, item="Watermelon War 1856",
     text="Stupidity rating, ten extra juicy watermelon slices out of ten.",
     env="city", scene="one stick character holding ten watermelon slices in a falling tower",
     face="funny strain, wide eyes"),
# ---------- 20. KARANSEBES 1788 (Part 11: beats 137-143) ----------
dict(n=137, part=11, item="Karánsebes 1788",
     text="Number twenty is the legendary Battle of Karánsebes, seventeen eighty-eight.",
     env="night", scene="one stick soldier holding a bottle near a campfire, dark forest tents",
     face="tipsy happy funny face"),
dict(n=138, part=11, item="Karánsebes 1788",
     text="Austrian soldiers got drunk and argued about who owned the schnapps.",
     env="night", scene="two stick soldiers arguing over a bottle by firelight, night sky",
     face="both drunk angry funny faces"),
dict(n=139, part=11, item="Karánsebes 1788",
     text="Someone fired a shot into the darkness entirely by complete accident.",
     env="night", scene="one stick soldier firing a musket upward, flash, others shocked",
     face="shocked startled face"),
dict(n=140, part=11, item="Karánsebes 1788",
     text="Panic spread, soldiers shot each other, and the cavalry charged in.",
     env="night", scene="stick soldiers running in panic, horse with stick rider, sparks",
     face="all panicked screaming faces"),
dict(n=141, part=11, item="Karánsebes 1788",
     text="Ten thousand Austrians wounded themselves, and no enemy was anywhere nearby.",
     env="night", scene="one stick soldier bandaging another, empty dark field behind",
     face="sad confused tired faces"),
dict(n=142, part=11, item="Karánsebes 1788",
     text="The Ottoman army arrived later and laughed hard at the whole mess.",
     env="night", scene="one stick Ottoman soldier laughing hard, mess of Austrians behind",
     face="huge open laugh"),
dict(n=143, part=11, item="Karánsebes 1788",
     text="Stupidity rating, eleven whole tiny schnapps bottles out of ten.",
     env="night", scene="one stick character surrounded by eleven bottle shapes, laughing",
     face="tipsy funny laugh"),
# ---------- 21. HONEY WAR 1839 (Part 11: beats 144-150) ----------
dict(n=144, part=11, item="Honey War 1839",
     text="Number twenty-one is the surprisingly sweet Honey War of eighteen thirty-nine.",
     env="farm", scene="one stick beekeeper with a bee hat holding honeycomb, flowers",
     face="happy gentle smile"),
dict(n=145, part=11, item="Honey War 1839",
     text="Missouri and Iowa argued fiercely about where the border actually was.",
     env="farm", scene="two stick men arguing at a tiny broken sign in a field",
     face="angry stubborn both"),
dict(n=146, part=11, item="Honey War 1839",
     text="A sheriff tried to collect honey taxes from farmers in Iowa.",
     env="farm", scene="one stick sheriff with a tax paper, beehives, bees flying",
     face="stern, bees annoying him"),
dict(n=147, part=11, item="Honey War 1839",
     text="Both governors raised angry little militias over the one hive.",
     env="hill", scene="two stick governors pointing, tiny militias behind, hive between",
     face="angry dramatic frowns"),
dict(n=148, part=11, item="Honey War 1839",
     text="No shots were fired, only sweet honey jokes flew around everywhere.",
     env="farm", scene="one stick beekeeper laughing, honey dripping from a jar",
     face="laughing open mouth"),
dict(n=149, part=11, item="Honey War 1839",
     text="The border is now just a peaceful line through a park.",
     env="farm", scene="one stick family picnicking on a park lawn, tiny line of grass",
     face="happy relaxed smiles"),
dict(n=150, part=11, item="Honey War 1839",
     text="Stupidity rating, seven sticky jars of honey out of ten.",
     env="farm", scene="one stick character holding seven honey jars, bees buzzing around",
     face="funny strained smile"),
# ---------- 22. DOG TAX WAR 1898 (Part 12: beats 151-157) ----------
dict(n=151, part=12, item="Dog Tax 1898",
     text="Number twenty-two is the amazing Dog Tax War of eighteen ninety-eight.",
     env="village", scene="one stick Māori chief with a brave dog, village huts behind",
     face="proud serious face"),
dict(n=152, part=12, item="Dog Tax 1898",
     text="New Zealand taxed every dog, and Māori hunters refused to pay it.",
     env="village", scene="one stick tax collector with a paper, angry hunter with dog",
     face="collector stern, hunter stubborn"),
dict(n=153, part=12, item="Dog Tax 1898",
     text="Officials marched into villages to collect the outstanding dog money.",
     env="village", scene="one stick official marching with a ledger, dogs barking",
     face="pompous determined face"),
dict(n=154, part=12, item="Dog Tax 1898",
     text="A small scuffle happened, and then everybody just went home.",
     env="village", scene="stick villagers and official dusting off, dogs looking guilty",
     face="awkward sheepish faces"),
dict(n=155, part=12, item="Dog Tax 1898",
     text="The dogs were completely innocent, as dogs always always are.",
     env="village", scene="one very innocent dog with huge sad eyes, spotlight",
     face="dog big innocent eyes"),
dict(n=156, part=12, item="Dog Tax 1898",
     text="The tax was quietly cancelled, and all the dogs celebrated wildly.",
     env="village", scene="one dog jumping with confetti, stick chief watching proud",
     face="happy dog tongue out, chief proud"),
dict(n=157, part=12, item="Dog Tax 1898",
     text="Stupidity rating, six extremely loyal good dogs out of ten.",
     env="village", scene="one stick character with six dogs on leashes, all pulling different ways",
     face="funny strain, dogs happy"),
# ---------- 23. OYSTER WAR 1880s (Part 12: beats 158-164) ----------
dict(n=158, part=12, item="Oyster War 1880s",
     text="Number twenty-three is the Oyster War of the eighteen eighties.",
     env="marsh", scene="one stick waterman holding a giant open oyster, marsh reeds",
     face="proud salty grin"),
dict(n=159, part=12, item="Oyster War 1880s",
     text="Greedy pirates raided the Chesapeake Bay's most precious oyster beds.",
     env="marsh", scene="one stick pirate with an eyepatch scooping oysters into a bag",
     face="greedy sneaky grin"),
dict(n=160, part=12, item="Oyster War 1880s",
     text="Maryland built a whole police force made entirely of oyster boats.",
     env="marsh", scene="one stick police boat captain with a badge, oysters in sight",
     face="serious official flat brows"),
dict(n=161, part=12, item="Oyster War 1880s",
     text="They chased oyster smugglers across the whole wide muddy bay.",
     env="marsh", scene="one stick officer in a small boat chasing a pirate boat, splashing",
     face="determined chase face"),
dict(n=162, part=12, item="Oyster War 1880s",
     text="Boats rammed each other over shellfish on very dark nights.",
     env="night", scene="two stick boats bumping in the dark, oyster shells flying",
     face="surprised bumping faces"),
dict(n=163, part=12, item="Oyster War 1880s",
     text="The oyster navy still exists today and guards the precious shellfish.",
     env="marsh", scene="one stick navy officer saluting a giant oyster, sunrise",
     face="proud serious smile"),
dict(n=164, part=12, item="Oyster War 1880s",
     text="Stupidity rating, fresh oysters eight shucked ones out of ten.",
     env="marsh", scene="one stick character with a plate of eight oysters, funny grin",
     face="happy greedy grin"),
# ---------- 24. COW WAR 1931 (Part 13: beats 165-171) ----------
dict(n=165, part=13, item="Cow War 1931",
     text="Number twenty-four is the Iowa Cow War of nineteen thirty-one.",
     env="farm", scene="one stick farmer with a cow, barn and windmill behind",
     face="grumpy stubborn frown"),
dict(n=166, part=13, item="Cow War 1931",
     text="Farmers fought state vets over cow tuberculosis testing rules, okay.",
     env="farm", scene="one stick vet with a big needle, farmer blocking with arms",
     face="vet serious, farmer angry"),
dict(n=167, part=13, item="Cow War 1931",
     text="The vets wanted to test cows, and the farmers said no way.",
     env="farm", scene="one stick vet pointing at a cow, farmer crossing arms in front",
     face="both stubborn angry faces"),
dict(n=168, part=13, item="Cow War 1931",
     text="The governor called out the National Guard to help resolve everything.",
     env="farm", scene="one stick governor on a podium, soldiers marching to a farm",
     face="official serious face"),
dict(n=169, part=13, item="Cow War 1931",
     text="Soldiers guarded the cows while vets tested them one by one.",
     env="farm", scene="one stick soldier saluting a cow, vet checking it with a chart",
     face="soldier serious, cow bored"),
dict(n=170, part=13, item="Cow War 1931",
     text="The cows just mooed loudly, and the farmers finally let everything go.",
     env="farm", scene="one stick cow mooing loudly, farmers shrugging, soldiers relaxing",
     face="cow funny loud mouth, farmers tired"),
dict(n=171, part=13, item="Cow War 1931",
     text="Stupidity rating, unimpressed cows five great cows out of ten.",
     env="farm", scene="one stick farmer with five cows, all staring unimpressed",
     face="farmer strained, cows bored"),
# ---------- 25. BEER FLOOD 1814 (Part 13: beats 172-178) ----------
dict(n=172, part=13, item="Beer Flood 1814",
     text="Number twenty-five is the London Beer Flood of eighteen fourteen.",
     env="city", scene="one stick brewer in an apron pointing at giant wooden barrels",
     face="proud worried grin"),
dict(n=173, part=13, item="Beer Flood 1814",
     text="A brewery's giant vat burst open and drowned the entire street.",
     env="city", scene="one stick person running from a huge foamy beer wave, buildings",
     face="terrified wide open mouth"),
dict(n=174, part=13, item="Beer Flood 1814",
     text="Over a million liters of porter destroyed many nearby brick houses.",
     env="city", scene="one stick person floating on a barrel in brown beer, houses knocked",
     face="shocked floating mouth open"),
dict(n=175, part=13, item="Beer Flood 1814",
     text="Eight people died, which sounds impossible but unfortunately really happened.",
     env="city", scene="one sad stick person with a hat in hand, beer puddle calm",
     face="sad droopy brows"),
dict(n=176, part=13, item="Beer Flood 1814",
     text="The brewery was forced to remove all of its giant wooden vats.",
     env="city", scene="one stick workman pushing a giant empty barrel away, sign blank",
     face="tired strained face"),
dict(n=177, part=13, item="Beer Flood 1814",
     text="Londoners still remember the terrible night the beer attacked the town.",
     env="city", scene="one stick old man telling a story to a small stick kid, beer mug",
     face="dramatic storytelling face, kid amazed"),
dict(n=178, part=13, item="Beer Flood 1814",
     text="Stupidity rating, six foamy giant beer barrels out of ten.",
     env="city", scene="one stick character covered in foam holding six tiny barrels",
     face="funny foamy strained face"),
# ---------- 26. LIGHT BRIGADE 1854 (Part 14: beats 179-185) ----------
dict(n=179, part=14, item="Light Brigade",
     text="Number twenty-six is the Charge of the Light Brigade, eighteen fifty-four.",
     env="hill", scene="one stick cavalry officer on a horse with a sword, hills",
     face="brave determined face"),
dict(n=180, part=14, item="Light Brigade",
     text="A wrong order sent six hundred cavalry into a valley of cannons.",
     env="hill", scene="one stick officer pointing the wrong way, cannons in a valley",
     face="confident mistaken face"),
dict(n=181, part=14, item="Light Brigade",
     text="They charged into the wrong valley and got absolutely wrecked completely.",
     env="hill", scene="one stick rider charging, cannon smoke ahead, panic",
     face="panicked wide eyes shouted mouth"),
dict(n=182, part=14, item="Light Brigade",
     text="Over a hundred men fell before the stupid order was finally fixed.",
     env="hill", scene="one sad stick rider with empty saddle beside, quiet hills",
     face="sad shocked droopy brows"),
dict(n=183, part=14, item="Light Brigade",
     text="The proud commander blamed one little completely misunderstood written order.",
     env="room", scene="one stick commander shrugging at a paper, other officers fuming",
     face="awkward guilty smirk"),
dict(n=184, part=14, item="Light Brigade",
     text="A poet wrote a sad poem about it, and everyone cried heavily.",
     env="room", scene="one stick poet with a quill writing, readers crying small tears",
     face="dramatic emotional face"),
dict(n=185, part=14, item="Light Brigade",
     text="Stupidity rating, nine very brave toy horses out of ten.",
     env="hill", scene="one stick character with nine tiny toy horses, funny salute",
     face="proud strained funny face"),
# ---------- OUTRO (Part 14: beats 186-192) ----------
dict(n=186, part=14, item="OUTRO",
     text="That was our list, but the real winner is clearly humanity itself.",
     env="desk", scene="one stick character presenting a huge trophy to a crowd of stick people",
     face="proud warm smile"),
dict(n=187, part=14, item="OUTRO",
     text="We almost forgot the War of the Oranges and the Banana Wars.",
     env="desk", scene="one stick character juggling an orange and a banana, books around",
     face="amused playful grin"),
dict(n=188, part=14, item="OUTRO",
     text="History keeps supplying us with new silly material every single year.",
     env="desk", scene="one stick character writing in a giant open book, calendar leaves falling",
     face="excited amazed open smile"),
dict(n=189, part=14, item="OUTRO",
     text="If you enjoyed this video, please share it with a history lover.",
     env="desk", scene="one stick character pointing at a giant blank share button",
     face="warm friendly smile"),
dict(n=190, part=14, item="OUTRO",
     text="And please remember, never ever start a war over a bucket.",
     env="farm", scene="one stick character shaking a finger at a wooden bucket, funny serious",
     face="mock-serious stern face"),
dict(n=191, part=14, item="OUTRO",
     text="Thanks so much for watching, and please stay safe out there.",
     env="desk", scene="one stick character waving goodbye, desk and lamp cozy",
     face="warm waving smile"),
dict(n=192, part=14, item="OUTRO",
     text="Also, please never fight the emus. They clearly won the last time.",
     env="desert", scene="one stick character waving a white flag, smug emu with crown, sunset",
     face="nervous smile, emu smug"),
]

def wc(t):
    return len(t.split())

def total_seconds(speed=1.35):
    return sum(wc(b["text"]) / 205.0 * 60.0 for b in BEATS)

if __name__ == "__main__":
    bad = [b["n"] for b in BEATS if not (10 <= wc(b["text"]) <= 12)]
    print(f"beats={len(BEATS)} parts={max(b['part'] for b in BEATS)}")
    print(f"word-count violations: {bad}")
    print(f"avg words/beat={sum(wc(b['text']) for b in BEATS)/len(BEATS):.1f}")
    print(f"estimated runtime at 205wpm: {total_seconds()/60:.2f} min "
          f"({total_seconds():.0f}s); w/ +0.15s tail: {sum(wc(b['text'])/205*60+0.15 for b in BEATS)/60:.2f} min")
